version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  db:
    image: "postgres:13.7-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_store
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data

