# Generated by Django 4.0.5 on 2022-06-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='googl_id',
            new_name='google_id',
        ),
    ]
