# Generated by Django 4.0.5 on 2022-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googl_id', models.IntegerField()),
                ('order_number', models.CharField(max_length=64)),
                ('price_us', models.IntegerField()),
                ('will_arrive', models.DateField()),
            ],
        ),
    ]
