# Generated by Django 4.0.5 on 2022-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0002_rename_googl_id_order_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_ru',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='google_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_us',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_arrive',
            field=models.DateField(null=True),
        ),
    ]
