# Generated by Django 4.0.5 on 2022-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0003_order_price_ru_alter_order_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_us',
            field=models.FloatField(null=True),
        ),
    ]
