# Generated by Django 4.0.5 on 2022-06-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0004_alter_order_price_ru_alter_order_price_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isValid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
