# Generated by Django 4.0.5 on 2022-06-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0005_order_isvalid_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isValid',
            new_name='is_valid',
        ),
    ]
